### PR TITLE
Improved performance by using PIL for edge detection and cache CIE image

### PR DESCRIPTION
**Pull request by jrast**
Hi David!

I improved the performance slightly by creating a CIE image once instead of many calls to the cie function. I also replaced the edge detection algorithm with PIL builtin functions.
Are you interested in improvements like this? I was working once with the original smartcrop and now found your more pythonic fork which is a lot easier to improve. So if you are interested I will provide some more improvements.

### CODE REVIEW

**Comment by davidfischer-ch** [comment]
Hi Jürg!

Thank you for contributing in making this library better, I appreciate your pull request very much!

Do you have any test images (in -> out) to check if the algorithm provide the same or better results?

In the meantime, I will test your version with some images.

Best Regards,

David Fischer

PS : I am already testing the code (private project's integration tests) but would like to setup some tests, with images embed into a sub-module to keep them separated from the code.

**Comment by davidfischer-ch** [comment]
Thanks!

**Comment by jrast** [comment]
Note that my changes will possibliy result in slightly different results. 

 - I have changed the CIE transformation to use the correct values (See https://github.com/jwagner/smartcrop.js/issues/77) 
 - The edge detection now works based on a integer image, resulting in slightly different edges.

But all in all I found not to much differences.

Yea, some tests would be nice. But how to automate the tests? We can not test on exact matches because slightly different crops are also ok.

**Comment by davidfischer-ch** [comment]
Yes it was I expected, but the results does not seem better or worse, most of the time they are identical.
I just added a small script to simplify executing smartcrop.py on a bunch of source images.

Example usage : ./test.py smartcrop1.py smartcrop2.py -s tests/source/ -t tests/target/

**Comment by davidfischer-ch** [comment]
To automate tests, have a bunch of test images available, and check the resulting crop coordinates (and not images) with what is expected from a previous run of the algorithm, specified into a YAML fixture file for example.

I may start this initiative but your are welcome to lead i ^^ if you have time.

**Comment by davidfischer-ch** [comment]
We can take v0.2 as the initial version ^^

**Comment by jrast** [comment]
Ok, i'll try to set up some tests (probably using pytest for this). I think it would be good to inform @hhmato to see if he still has interest in this project, if so, I think it would be fair to merge back the changes in this repo to his repository.

**Pull request merged**
